# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('nota', models.PositiveSmallIntegerField(max_length=2)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='formulario',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr.Loja'),
        ),
    ]
