# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='legenda',
            field=models.CharField(choices=[('Outros', 'Outros'), ('Pre\xe7o Elevado', 'Pre\xe7o Elevado'), ('Ruptura', 'Ruptura'), ('Produto Indisponivel', 'Produto Indisponivel'), ('Loja', 'Loja'), ('Embalagem', 'Embalagem'), ('Sugest\xe3o', 'Sugest\xe3o'), ('Atendimento', 'Atendimento'), ('Variedade de Produtos', 'Variedade de Produtos'), ('Qualidade de Produtos', 'Qualidade de Produtos')], default='-', max_length=30),
        ),
    ]
