# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0002_formulario_legenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='legenda',
            field=models.CharField(choices=[('Outros', 'Outros'), ('Preco Elevado', 'Preco Elevado'), ('Ruptura', 'Ruptura'), ('Produto Indisponivel', 'Produto Indisponivel'), ('Loja', 'Loja'), ('Embalagem', 'Embalagem'), ('Sugest\xe3o', 'Sugestao'), ('Atendimento', 'Atendimento'), ('Variedade de Produtos', 'Variedade de Produtos'), ('Qualidade de Produtos', 'Qualidade de Produtos')], default='-', max_length=30),
        ),
    ]
